NAME = defesa

OTHER += $(LILY_PDF) $(PNG_PDF) $(GNUPLOT_PDF) $(SVG_PDF)

USE_PDFLATEX = 1

-include ~/repositorios/genos-repos/lib/make/latex.mk

light-clean:
	rm -f $(NAME).{aux,lo*,ps,pdf,bl*,dvi,to*,bb*,nav,out,snm}
