* porque repetição/ostinato?
* porque quinteto de metais?
** gosto de música de câmara
** gosto da formação
** é mais fácil conseguir um quinteto do que uma orquestra.
* poderia ter feito a musica sem contornos?
** não. o contorno está inserido em toda a estrturação da obra.
** pensei em contornos ao compor os principais elementos da obra
** os contornos não estão apenas nos elementos musicais, mas no pensamento: "como posso usar contornos aqui?"
* porque contornos?
** contornos são estruturas situadas em um nível mais alto de abstração do que altura/duração. está mais próximo do compositor
** relações de contornos melódicos são mais facilmente percebidos por ouvintes do que relações de altura
** contornos podem ser associados a diversos parâmetros musicais como proporção, dinâmica, andamento, densidade, textura, etc.
** contornos permitem operações e combinações de operações
* pensa em motivos?
** sim, um motivo principal (g e fis cis dis c), e suas derivações

%%% Local Variables: 
%%% mode: org
%%% End:
