NAME = dissertacao-default
TEXSRCS = body-pt.tex abstract.tex

OTHER += $(LILY_EPS)

-include ~/lib/make/latex.mk
-include ~/repositorios/genos-repos/lib/make/latex.mk

light-clean:
	rm -f dissertacao-default.{aux,lo*,ps,pdf,bl*,dvi,to*,bb*}
	rm -f dissertacao-simples.{aux,lo*,ps,pdf,bl*,dvi,to*,bb*}
